name: "jmattschey.github.io"  
author: "Jennifer Mattschey"  
output_dir: "."  
output:  
  html_document:  
    self_contained: no  
    theme: flatly
    css: style.css
navbar:  
  title: "Jennifer Mattschey" 
  right:
    - text: "Home"
      href: index.html
    - text: "Blog"
      href: blog.html
    - text: "Teaching Resources"
      href: Teaching.html
    - text: "Research"
      href: Research.html
    - text: "CV"
      href: "cv.pdf"
      
